### ISSUE TITLE
Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by x80486** [flathub/com.bitwarden.desktop#1]
I see a lot of these when I query the contents of the `systemd(1)` journal:

```sh
Sep 05 06:55:44 uplink electron[23948]: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Sep 05 06:55:54 uplink electron[23948]: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Sep 05 06:55:55 uplink electron[23948]: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Sep 05 06:56:04 uplink electron[23948]: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Sep 05 06:56:14 uplink electron[23948]: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

I isolated (read: shutdown/closed) all Electron apps, so I'm sure this is coming from `Bitwarden`. I can't run the `AppImage` anymore to see if that happens also with that one.

Just filing this one to let you know...in case those are relevant.

Cheers / me

**Comment by ghisvail** [comment]
You did well. I'll investigate.

**Comment by ghisvail** [comment]
@x80486 Are you running on KDE or GNOME? A quick lookup of the error revealed the issue may come from [node-keytar](https://github.com/atom/node-keytar/issues/74) and the absence of `gnome-keyring` on the host system.

**Comment by x80486** [comment]
I don't see those messages anymore. This is OK :+1:

**Comment by shanon955** [comment]
I am a learner
Dont you  think that secret desktop means opened door to google psycho control?
