### ISSUE TITLE
Login  fails on Rapsberry PI4

### ISSUE THREAD

**Issue by Dag3105** [flathub/com.bitwarden.desktop#101]
Hi,
after typing the credentials it produces the following error: an unexpected error has occurred.

Thanks for Your attention, bye.

![image](https://user-images.githubusercontent.com/83144935/167413636-61ad0610-cf10-4509-ba8e-8b1d5a79de12.png)

**Comment by ghisvail** [comment]
This Flatpak in only built and updated for x86 architectures. I can't help you running it on ARM.

**Comment by Dag3105** [comment]
Thx
