### ISSUE TITLE
Bitwarden icon looks bad in big size

### ISSUE THREAD

**Issue by crbelaus** [flathub/com.bitwarden.desktop#11]
The Bitwarden icon looks very bad when it is displayed using big size. In the following screenshot both Bitwarden, Telegram and Spotify are Flatpaks, but only Bitwarden has this problem.

![bitwarden-window-switcher](https://user-images.githubusercontent.com/2965623/52901436-cbfa9b00-3203-11e9-99dd-d6684b86784b.png)

I am using Linux Mint 19.1 and the Bitwarden package installed from FlatHub:

```
$ flatpak info com.bitwarden.desktop
Ref: app/com.bitwarden.desktop/x86_64/stable
ID: com.bitwarden.desktop
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-09-05 12:16:39 +0000
Subject: Enable access to secrets (f32239a3)
Commit: 641c2213c1a61dd18a5e8ffe15cecb01d1192731af94c3f6e7b16297f0c2a462
Parent: bfac8442abbc1b886c2aca8fb27bce2bd0909e9b6871a250f6c389bbe95375a2
Location: /var/lib/flatpak/app/com.bitwarden.desktop/x86_64/stable/641c2213c1a61dd18a5e8ffe15cecb01d1192731af94c3f6e7b16297f0c2a462
Installed size: 757,1 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
```

**Comment by ghisvail** [comment]
Could you verify whether the problem still exists with the new version?

**Comment by crbelaus** [comment]
The problem its now gone. Thank you @ghisvail :raised_hands:
