### ISSUE TITLE
Version number not being updated when flathubbot commits new release

### ISSUE THREAD

**Issue by danielgarciagarcia** [flathub/com.bitwarden.desktop#116]
When a new Bitwarden version is released, Flatpak detects it on my system and I can install it. However, the version number seems to be stuck with the "2022.5.0" string. I guess that's because it's not being added by flathubbot to the com.bitwarden.desktop.appdata.xml file. 

This means that not only flatpak doesn't know the new version number, but also third party software managers such as GNOME Software (they detect newer versions but not the number change). Bitwarden's Flathub site will also contain outdated information (at the moment, it shows that the latest version is 2022.5.0, updated on June 3, 2022, but when it installs 2022.8.1).

**Comment by ghisvail** [comment]
You are right. Somehow, the bot missed updating the application metadata although it used to it properly in the past.
