### ISSUE TITLE
error: Unable to allocate instance id

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/com.bitwarden.desktop#118]
"https://github.com/flathub/org.signal.Signal/issues/122#issue-578550725" and
```
su -c 'flatpak update'
Last metadata expiration check: 3:12:31 ago on Fri Sep  2 21:43:26 2022.
Dependencies resolved.
Nothing to do.
Complete!

Note that the directory 

'/root/.local/share/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.
```
may be relevant.

**Comment by ghisvail** [comment]
> Never mind, issue resolved when PC was rebooted.

Did it work for you?

Not sure what else to suggest given the limited information available.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@ghisvail, indeed, remediated by reinitialization. Reported anyway because it was an error, despite the easy method of remediation.
