### ISSUE TITLE
Export Vault permissions

### ISSUE THREAD

**Issue by martin-jamszolik** [flathub/com.bitwarden.desktop#12]
Hi
bitwarden has a feature where you can export all your data as JSON or CSV.
In the current configuration, I cannot save that file anywhere due to sandbox restriction.
The workaround is to fire up the application in a command line as follows
`flatpak run --filesystem=home com.bitwarden.desktop`

This allows access to my home folder in the filestystem, at which point I am able to save and inspect the file.

Should we not add this to the default yaml configuration as well?

**Comment by x80486** [comment]
Granting `--filesystem=xdg-download` should be more than enough for this one.

**Comment by ghisvail** [comment]
Agreed.
