### ISSUE TITLE
Unable to login on current stable

### ISSUE THREAD

**Issue by sfalken** [flathub/com.bitwarden.desktop#137]
OS: openSUSE microOS Desktop Plasma
DE: Plasma 5.27/Wayland

When trying to use, I get the following error:
![Screenshot_20230305_095544](https://user-images.githubusercontent.com/95936027/222977417-4ee0fa5b-80fb-45e9-badc-395d73ea499a.png)

Output of 'flatpak run -v com.bitwarden.desktop'

https://paste.opensuse.org/pastes/8798b1b74c25

I've poked around in flatseal a bit, without any luck getting it to work.

**Comment by ioanrogers** [comment]
I was also having this issue, but as of the 2023.12.0 flatpak I can now log in.

**Comment by ghisvail** [comment]
Please reopen if still happening. The issue was likely transient and should not be present today.
