### ISSUE TITLE
An unknown file called "salt" starting showing up

### ISSUE THREAD

**Issue by Scotty-Trees** [flathub/com.bitwarden.desktop#140]
I've been running Fedora Gnome 37 since it's release, never any issues. Today I noticed a new, yet unknown file in my home directory called "salt" and it's only 8 bytes so while it's not much in terms of size, I did not create it and no application that I know of uses it. I've tracked my app using down to it being Bitwarden (flatpak) as the most likely culprit. I have not installed any new applications recently, so this came as a bit of a shock. Not sure if it's just some random, harmless little bug from somewhere or if I should be at all concerned about this.

![Screenshot from 2023-03-21 19-45-13](https://user-images.githubusercontent.com/45135187/227630525-dc36f014-a7f3-42e5-b757-c83ef3034b40.png)

Feel free to let me know if you have any information about seeing this and/or if you need any additional information from me please don't hesitate to ask. When I try to open the file it says "Could not display salt, the file is of an unknown type" so I'm wondering if it's anything nefarious or not or if I could safely delete it. All my applications have been installed from dnf, flatpak, or gnome software, I haven't used any copr repos or anything out of the ordinary; nothing was ever installed outside of the Fedora repos, Flatpak repos, or RPMFusion repos. My .bash_history file in my home directory shows nothing with 'salt' in it either, i've never used the word salt for anything on my computer, which is why I find this odd. So please let me know if this is a result from a possible recent update to Bitwarden's flatpak version, thank you.

Btw, when I open the file 'salt' with Text Editor, this is all I see:

![Screenshot from 2023-03-21 20-50-12](https://user-images.githubusercontent.com/45135187/227630808-a70236f1-ff8f-433d-894e-b30cfccdb947.png)

**Comment by ghisvail** [comment]
No idea. Please consider forwarding your issue upstream, if it has not been already reported by someone else.

**Comment by ghisvail** [comment]
Closing as won't fix
