### ISSUE TITLE
Autostart requires write permission to home directory

### ISSUE THREAD

**Issue by Hinton** [flathub/com.bitwarden.desktop#156]
From https://github.com/bitwarden/clients/issues/6181

The autostart functionality attempts to write a file to the `~/.config/autostart` directory of the users home directory. This fails since the flatpack bundle only has the `--filesystem=xdg-download` permission.

I believe adding `--filesystem=home` would resolve this, but it also provides filesystem access to the application.

**Comment by ghisvail** [comment]
It should work with the following override (assuming Bitwarden is installed in user mode):

`flatpak override --user --filesystem=xdg-config/autostart com.bitwarden.desktop`

Could you verify it?
