### ISSUE TITLE
[Bug] Incorrect Licensing

### ISSUE THREAD

**Issue by Cyanide-1** [flathub/com.bitwarden.desktop#157]
Bitwarden is under GPLv3-only. Flathub shows this as being proprietary when Bitwarden is fully open source under GPLv3-only license. I suggest fixing this issue, thank you.

**Comment by ghisvail** [comment]
There is [no issue](https://github.com/flathub/com.bitwarden.desktop/blob/8fb5d6ffae9e51f8954024f176674eea9843c33c/com.bitwarden.desktop.metainfo.xml#L7) on our end.

There is an open issue on [flathub/website](https://github.com/flathub/website/issues/1930) reporting that *all* apps are displayed as `Proprietary`.

Next time, please consider doing a bit more research.

Thanks 👍

**Comment by Cyanide-1** [comment]
oh wow, that's weird, flathub needs to fix that then
