### ISSUE TITLE
Copy password feature not working on KDE

### ISSUE THREAD

**Issue by ghisvail** [flathub/com.bitwarden.desktop#173]
## Problem
Copy not working

### System specs
- Operating System: Fedora Linux 39
- KDE Plasma Version: 5.27.9
- KDE Frameworks Version: 5.111.0
- Qt Version: 5.15.11
- Kernel Version: 6.6.3-200.fc39.x86_64 (64-bit)
- Graphics Platform: Wayland
- Bitwarden version: 2023.10.1 of bitwarden

### Current behavior 
1. Go to 'record'
2. Click on 'copy password'
3. Go to the place
4. ctrl + v and nothing happens
5. Go to 'record'
6. Click on show password
7. ctrl + c
8. Go to place of usage
9. ctr + v and now paste the value

### Expected behavior
1. Go to 'record'
2. Click on 'copy password'
3. Go to the place
4. ctrl + v pase the value

_Originally posted by @galloramiro in https://github.com/flathub/com.bitwarden.desktop/issues/147#issuecomment-1840881831_

**Comment by eylenburg** [comment]
I have the same issue with KDE 5.27.9 Wayland on OpenSUSE Tumbleweed.

I downloaded the official Bitwarden AppImage to check, and copying works. **So this is a Flatpak-related bug.**

**Comment by galloramiro** [comment]
@ghisvail thanks for coping this into is own issue. 
I wasn't sure about it. 

Today I updated into the 2023.12.0 v and the error persist.

**Comment by galloramiro** [comment]
Hi @ghisvail, just to know, if there any plan to solve this? there is anything I can do to help? 
Thanks

**Comment by ghisvail** [comment]
Unfortunately, I am neither a KDE user, nor do I know a KDE expert who can help. If you know someone, feel free to direct him or her here.

**Comment by mellodoot** [comment]
can confirm this issue persists on fedora 39, KDE 5.27.10 on wayland. copying to clipboard doesn't appear to work for any field across the app (tested username, password, and TOTP).

this appears to be exclusive to the flathub version, so fellow fedora users can lean on the official rpm package listed on their [download page](https://bitwarden.com/download/) (though they do warn this provides no automatic updates, so use at your discretion). the .appimage release also appears to work without issue, unsure about the .deb package.

**Comment by 3DMicks** [comment]
This issue is still present in Arch KDE Plasma 5.27.10.

My current "workaround" is to run `flatpak run com.bitwarden.desktop --ozone-platform=x11` to force it to use xwayland.
If it still tries to use Wayland, you'll need to disable `socket=wayland` in the flatpak permissions. I recommend using Flatseal.

**Comment by galloramiro** [comment]
> This issue is still present in Arch KDE Plasma 5.27.10.
> 
> My current "workaround" is to run `flatpak run com.bitwarden.desktop --ozone-platform=x11` to force it to use xwayland. If it still tries to use Wayland, you'll need to disable `socket=wayland` in the flatpak permissions. I recommend using Flatseal.

Thats a good one, do you know if there is any way of runing this with out making it an alias on the console? hahaha

**Comment by eylenburg** [comment]
> > This issue is still present in Arch KDE Plasma 5.27.10.
> > My current "workaround" is to run `flatpak run com.bitwarden.desktop --ozone-platform=x11` to force it to use xwayland. If it still tries to use Wayland, you'll need to disable `socket=wayland` in the flatpak permissions. I recommend using Flatseal.
> 
> Thats a good one, do you know if there is any way of runing this with out making it an alias on the console? hahaha

Just edit the starter in the KDE Menu Editor:

![Bitwarden](https://github.com/flathub/com.bitwarden.desktop/assets/84839316/043eae6e-53fa-4ecd-b7d4-97b59f6ce06c)

**Comment by noelmiller** [comment]
I am also running into this issue. When I disable wayland to resolve this the app does not start. What do I need to change in Flatseal to successfully run with the workaround?
```
[2:0201/151248.372697:ERROR:wayland_connection.cc(193)] Failed to connect to Wayland display: No such file or directory (2)
[2:0201/151248.372727:ERROR:ozone_platform_wayland.cc(259)] Failed to initialize Wayland platform
[2:0201/151248.372730:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
```

**Comment by noelmiller** [comment]
Another option as a workaround is to use the Official [AppImage](https://vault.bitwarden.com/download/?app=desktop&platform=linux) using [GearLever](https://flathub.org/apps/it.mijorus.gearlever) to integrate it into your desktop. 

I would prefer the flatpak to work properly on KDE, but I can't figure out how to get it to work using Flatseal or creating a separate custom `.desktop` file..

**Comment by thatLeaflet** [comment]
I'm experiencing this issue on Gnome too. Someone created a patch to fix it, it would be nice if it was integrated into the this flatpak version.

https://github.com/solopasha/bitwarden_flatpak/blob/build-from-source/wayland-clipboard.patch

**Comment by ghisvail** [comment]
> Someone created a patch to fix it, it would be nice if it was integrated into the this flatpak version.

This patch needs to be forwarded and integrated upstream to benefit all distributions.

**Comment by ghisvail** [comment]
Looks like there is a PR opened for a proposal for a fix:

https://github.com/bitwarden/clients/pull/7508

**Comment by 3DMicks** [comment]
As of the `2024.3.0` update https://github.com/flathub/com.bitwarden.desktop/commit/a0f1bd195e4da6df13fa905ebf4e1da8adf5b5cc, copying seems to be working fine. Although Bitwarden now takes a very long time to open.

**Comment by ghisvail** [comment]
Works on KDE Neon running Plasma 6 on Wayland

**Comment by galloramiro** [comment]
Hi @ghisvail today seems to be working. 
But last moth works for some days and then stop working again. 
I would check this week and if keeps working I would confirm here. 
Thanks!

**Comment by galloramiro** [comment]
Working here!
![Screenshot_20240318_164555](https://github.com/flathub/com.bitwarden.desktop/assets/25160187/63bae0ce-6bec-4980-b091-0a7b69ab65d2)
![Screenshot_20240318_164513](https://github.com/flathub/com.bitwarden.desktop/assets/25160187/9b07c86a-2ee9-4a83-baf0-6a4d66764979)

**Comment by quexten** [comment]
Seems to be fixed. If this re-occurs, please re-open here or in upstream bitwarden/clients. Thanks!
