### ISSUE TITLE
Feature: add optional Wayland support

### ISSUE THREAD

**Issue by thatLeaflet** [flathub/com.bitwarden.desktop#175]
Currently, if I want to run Bitwarden in native Wayland mode, I need to either (1) launch from the terminal and pass ozone flags or (2) modify the desktop file and add those flags. Neither method is particularly good.

I propose that this this Bitwarden flatpak should [follow in the steps of the Discord flatpak](https://github.com/flathub/com.discordapp.Discord/commit/a2f7a449af1af18a36e2547a2658cf5be5e986d5) and add an optional native Wayland mode. With the Discord flatpak, it by default only comes with X11 access. But if you grant it Wayland access, it will automatically launch in native Wayland mode.

The only issue I've run into with native Wayland is that right clicking the titlebar does not bring up the menu on Gnome (not an issue on other desktop environments that support server side decorations on Wayland).

**Comment by ghisvail** [comment]
The ozone flags are already [passed](https://github.com/flathub/com.bitwarden.desktop/blob/debceadbc38348ac3eb7eb5e1dfe479ead0976b5/com.bitwarden.desktop.yaml#L66).

Not sure what your issue is.

**Comment by thatLeaflet** [comment]
You're right! It was added last month, I missed that happening.
