### ISSUE TITLE
`org.freedesktop.portal.*` permission is not necessary

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.bitwarden.desktop#180]
This will be blocked in the linter soon. This issue is a heads-up for that.

See https://github.com/flathub-infra/flatpak-builder-lint/issues/178

**Comment by ghisvail** [comment]
Is it okay to just remove the line, or should it be replaced by something else?

**Comment by bbhtt** [comment]
Yes, please remove it, it should be working ootb
