### ISSUE TITLE
Update to 1.8.0

### ISSUE THREAD

**Issue by MrSquaare** [flathub/com.bitwarden.desktop#2]
Hello,
Can you update the Bitwarden application to its lastest version?

Thank you

**Comment by MrSquaare** [comment]
Thank you,

But when I download Bitwarden from Flathub, I still get version 1.7.0, and Flathub also indicates that the latest version is 1.7.0 (https://flathub.org/apps/details/com.bitwarden.desktop)

Also (very low demand), is it possible to name the application only "Bitwarden" (instead of Bitwarden Desktop currently)? Thank you.

**Comment by ghisvail** [comment]
Le dim. 30 sept. 2018 à 21:10, Guillaume Bonnet <notifications@github.com>
a écrit :

> Thank you,
>
> But when I download Bitwarden from Flathub, I still get version 1.7.0, and
> Flathub also indicates that the latest version is 1.7.0 (
> https://flathub.org/apps/details/com.bitwarden.desktop)
>
Indeed. The build system is currently failing due to the recent update to
webpack 4. To be investigated.

> Also (very low demand), is it possible to name the application only
> "Bitwarden" (instead of Bitwarden Desktop currently)? Thank you.
>
I am following the naming convention used  upstream.

**Comment by MrSquaare** [comment]
> Indeed. The build system is currently failing due to the recent update to webpack 4. To be investigated.
Ah, so it's from Flathub, then? And do you know if this problem has been around for a long time? Thank you

**Comment by FarrelF** [comment]
Hello, any news about Software Update for Bitwarden? The latest version of Bitwarden (1.9.0) it self was released just for few days ago. And, Flathub still indicates that the latest version is 1.7.0 until now :(

**Comment by ghisvail** [comment]
Last time I tried, the build was failing due to upstream upgrading to webpack 4, which does not play nice with offline builds for some reasons. I will give it another go.

**Comment by ghisvail** [comment]
Still getting a `ENOTCACHED` error although `extract-text-webpack-plugin` is listed in `generated-sources.json`:

```
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/extract-text-webpack-plugin failed: cache mode is 'only-if-cached' but no cached response available.
```

Not sure what's going on here.

**Comment by x80486** [comment]
Ouch! I submit #5 without reviewing these first. I currently have the same problems with s Flatpak I'm trying to do for "Standard Notes"...it just doesn't work.

Anyway...thanks for the effort! :trophy:
