### ISSUE TITLE
Tray icon don't work

### ISSUE THREAD

**Issue by fbodr** [flathub/com.bitwarden.desktop#23]
Even after enabling the tray icon in settings, it is still not visible

**Comment by TingPing** [comment]
Does this work:

`flatpak run --env=XDG_CURRENT_DESKTOP=Unity --talk-name=org.kde.StatusNotifierWatcher com.bitwarden.desktop`

**Comment by fbodr** [comment]
yes, that does work

**Comment by TingPing** [comment]
Will be done next update.
