### ISSUE TITLE
Running the application in the background

### ISSUE THREAD

**Issue by r3l4t1v** [flathub/com.bitwarden.desktop#28]
When running the application with the tray icon enabled, it shuts down completely when closing the main Bitwarden window. I'd have expected the application to continue running in the background, leaving only the tray icon.

Is this the intended behaviour or a bug?

OS: Fedora 31 and Fedora 32 beta
Bitwarden: 1.17.2

**Comment by ghisvail** [comment]
> Is this the intended behaviour or a bug?

No idea. Feel free to forward this issue upstream.

**Comment by ghisvail** [comment]
Did you try the [upstream rpm](https://github.com/bitwarden/desktop/releases/download/v1.17.2/Bitwarden-1.17.2-x86_64.rpm)?

**Comment by r3l4t1v** [comment]
The same thing occurs in the upstream rpm. Apologies and thanks for the help; closing this issue.
