### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by phloose** [flathub/com.bitwarden.desktop#32]
The current version of the bitwarden desktop app ist 1.19.0, whereas the flathub version is 1.18.0.

**Comment by ghisvail** [comment]
Thanks for reaching out. Feel free to submit a PR for the update.

Cheers,

Le ven. 24 juil. 2020 à 20:02, Philipp Loose <notifications@github.com> a
écrit :

**Comment by phloose** [comment]
> Feel free to submit a PR for the update.

Done with #33

**Comment by ghisvail** [comment]
Closed by #33
