### ISSUE TITLE
Application isn’t listed correctly by flatpak

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.bitwarden.desktop#6]
Version 1.7.0
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

Flatpak v1.0.4

Issue: Reverse DNS name is missing the last part (should be com.bitwarden.desktop). Every other app behaves fine, so I don’t think that this is an issue of Flatpak.
```
> flatpak search bitwarden
Application ID Version Zweig  Remotes Beschreibung                                               
com.bitwarden  1.7.0   stable flathub A secure and free password manager for all of your devices.
```

**Comment by ghisvail** [comment]
Nothing much to be done here, sadly.
