### ISSUE TITLE
Certificate bundles

### ISSUE THREAD

**Issue by Barracuda6** [flathub/com.bitwarden.desktop#65]
I am using the Bitwarden flatpak on an openSUSE host and it seems that Bitwarden is not detecting the self-signed CA certificates I have added to the system by adding the certificates to /etc/pki/trust/anchors and running update-ca-certificates. I am running a self-hosted Bitwarden server that uses a certificate signed by a self-signed CA. Could anyone offer any guidance here?

The symptom is that the UI returns the message "An error has occurred. Failed to fetch" and I see this message in the developer console: "Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID"

**Comment by SchnWalter** [comment]
It probably needs access to that directory. I'm not sure what `override --fliesystem` does to paths from `/etc`, but it works for non-system paths:
```
flatpak override --filesystem=/path/goes/here com.bitwarden.desktop
```

**Comment by ghisvail** [comment]
I wonder whether Bitwarden supports `SSL_CERT_DIR` like other Flatpak apps. If I provide a draft PR with it, could you test it @Barracuda6 ?

**Comment by ghisvail** [comment]
I don't use a self-hosted instance of Bitwarden so I can't test a tentative fix for this.

**Comment by Barracuda6** [comment]
> It probably needs access to that directory. I'm not sure what `override --fliesystem` does to paths from `/etc`, but it works for non-system paths:
> 
> ```
> flatpak override --filesystem=/path/goes/here com.bitwarden.desktop
> ```

I receive the error even if I enable access to the entire host filesystem.



> I wonder whether Bitwarden supports `SSL_CERT_DIR` like other Flatpak apps. If I provide a draft PR with it, could you test it @Barracuda6 ?

Sure, I would be happy to test.

**Comment by Barracuda6** [comment]
Unfortunately, #66 did not fix this for me. My CA certificate is present in /etc/ssl/certs but I still received ERR_CERT_AUTHORITY_INVALID in the developer console. I also tried adding --filesystem=/etc/ssl/certs which didn't help.

**Comment by ghisvail** [comment]
Then, we need input from the Flatpak community to understand how this issue can be fixed.

**Comment by Barracuda6** [comment]
It seems these types of issues are being discussed at https://github.com/flatpak/flatpak/issues/2721

**Comment by Barracuda6** [comment]
I gave the Bitwarden flatpak another try today and... it worked! I was able to log in. I'm not sure what has changed. I guess this issue could be closed.

**Comment by ghisvail** [comment]
Thanks for your heads up. Glad it worked out for you eventually.

Le ven. 20 août 2021 à 03:01, Barracuda6 ***@***.***> a
écrit :
