### ISSUE TITLE
The Global Menubar does not appear unless org.gtk.Gtk3theme.Breeze-Dark is forced.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/com.bitwarden.desktop#67]
The menubar does not appear, and the Global Menubar Plasmoid does not function for http://github.com/flathub/com.bitwarden.desktop unless http://github.com/flathub/org.gtk.Gtk3theme.Breeze-Dark is forced as `flatpak run --env=GTK_THEME=Breeze-Dark com.bitwarden.desktop`.

**Comment by beedell-roke** [comment]
This may be a downstream counterpart to [`bitwarden/clients/issues/17451`](https://github.com/bitwarden/clients/issues/17451#issuecomment-3562928963), which is due to [`flathub/org.gtk.Gtk3theme.Breeze/issues/170`](https://github.com/flathub/org.gtk.Gtk3theme.Breeze/issues/170#event-3973497240).

**Comment by quexten** [comment]
In case this is an issue, please report it upstream to https://github.com/bitwarden/clients, as per https://github.com/flathub/com.bitwarden.desktop/issues/324.

**Comment by beedell-roke** [comment]
@quexten, please re-close as a duplicate of [`bitwarden/clients/issues/17451`](https://github.com/bitwarden/clients/issues/17451#issuecomment-3562928963).

**Comment by quexten** [comment]
Thanks @RokeJulianLockhart  fixed.
