### ISSUE TITLE
Application can’t be started by command line

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.bitwarden.desktop#7]
Version 1.7.0
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

Flatpak v1.0.4

I cant start the application fine by the .desktop starter, but when I try to launch it via the command line, I the the following result reproducibly, whereby the application window doesn’t display the real content, but a frozen part of the other windows in the background of the application window:

```
$ flatpak run com.bitwarden.desktop

> bitwarden@0.0.0 start /app/main
> cross-env ELECTRON_IS_DEV=0 ELECTRON_NO_UPDATER=1 electron ./build
```

![bildschirmfoto von 2018-11-19 15-19-12](https://user-images.githubusercontent.com/10520767/48712720-c2ff2b00-ec0e-11e8-9861-95c89cfcfa48.png)

**Comment by ghisvail** [comment]
Fixed with the latest release.
