### ISSUE TITLE
bundling the cli client

### ISSUE THREAD

**Issue by andrewgdunn** [flathub/com.bitwarden.desktop#83]
Might be a tall ask, but would it be possible to consider bundling the [bw](https://bitwarden.com/help/article/cli/#download-and-install) command line client? It would make querying the password database possible from within scripts (would be very nice for a use case I'm playing with: replacing pass)

**Comment by ghisvail** [comment]
Sounds like a reasonable idea to me :+1: 

Would you like to try submit a PR for it? It would consist in just appending another module and untar the content of the `bw` binary to `"${FLATPAK_DEST}/bin"`
