### ISSUE TITLE
Fails to build since upgrade to webpack 4

### ISSUE THREAD

**Issue by ghisvail** [flathub/com.bitwarden.desktop#9]
See the following [comment](https://github.com/flathub/com.bitwarden.desktop/issues/2#issuecomment-432712670)

**Comment by x80486** [comment]
For the time being, I would consider _switching_ to the `.deb` approach, as many other Electron-based Flatpak manifests.

**Comment by ghisvail** [comment]
In the meantime, it seems the bitwarden devs published an official snap
package for the desktop client.

**Comment by x80486** [comment]
Yeah, but I can't use any of that. Do you want me to update the manifest to start using the `.deb` approach. `Wire` works in the same way, and generally that's accepted in Flathub if there are/were issues building the application the way it's done right now. You can keep the work as it is in a different branch and test from time to time...that's what I do for `Wire`, and still unsuccessful, so I keep using the `.deb` files for the time being.

Let me know...

**Comment by ghisvail** [comment]
Please, go ahead.

**Comment by kspearrin** [comment]
@x80486 

> For the time being, I would consider switching to the .deb approach, as many other Electron-based Flatpak manifests.

Do you have an example that can be referenced?

**Comment by x80486** [comment]
@kspearrin, you can take a look at [Wire](https://github.com/flathub/com.wire.WireDesktop/), or [this](https://github.com/flathub/com.bitwarden.desktop/pull/10/) pull request I sent a while back. I'm also trying to see if it can be built like [this](https://github.com/flathub/io.github.liberodark.OpenDrive/) one.

**Comment by kspearrin** [comment]
@x80486 

Why was your PR closed for the deb switch?

**Comment by x80486** [comment]
I closed it in favor or building it from sources via `YARN`, as Filippe did with `OpenDrive`...will try to send a pull request any time soon once I find some time.

**Comment by barthalion** [comment]
Any news? Personally, I wouldn't mind if we switched to x86_64-only deb repackaging for now.

**Comment by ghisvail** [comment]
@barthalion I'll look into it. I am also in favor of switching to the repackaging in the meantime.
