### ISSUE TITLE
Failed to start on Fedora 35

### ISSUE THREAD

**Issue by Bryan2333** [flathub/com.bitwarden.desktop#95]
When I tried to launch to app, it crashed.
Here are what I got when running flatpak run com.bitwarden.desktop in the terminal
```
$ flatpak run com.bitwarden.desktop
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote --enable-crashpad
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
```

**Comment by ghisvail** [comment]
In the interest of future users, what was the solution?

**Comment by Bryan2333** [comment]
Well, it can start normally at first, I just turned on an option in the flatseal by mistake. But I have forgot what it is.
